application: emr-mx
version: 1
runtime: python27
api_version: 1
threadsafe: yes

handlers:

- url: /app
  script: main.app

- url: /(.*\.css)
  mime_type: text/css
  static_files: static/\1
  upload: static/(.*\.css)

- url: /(.*\.html)
  mime_type: text/html
  static_files: static/\1
  upload: static/(.*\.html)

- url: /(.*\.js)
  mime_type: text/javascript
  static_files: static/\1
  upload: static/(.*\.js)

- url: /(.*\.txt)
  mime_type: text/plain
  static_files: static/\1
  upload: static/(.*\.txt)

- url: /(.*\.xml)
  mime_type: application/xml
  static_files: static/\1
  upload: static/(.*\.xml)

- url: /(.*\.eot)
  mime_type: application/x-font-eot
  static_files: static/\1
  upload: static/(.*\.eot)

- url: /(.*\.ttf)
  mime_type: application/x-font-ttf
  static_files: static/\1
  upload: static/(.*\.ttf)

- url: /(.*\.woff)
  mime_type: application/x-font-woff
  static_files: static/\1
  upload: static/(.*\.woff)

- url: /(.*\.otf)
  mime_type: application/x-font-otf
  static_files: static/\1
  upload: static/(.*\.otf)

- url: /(.*\.svg)
  mime_type: application/x-font-svg
  static_files: static/\1
  upload: static/(.*\.svg)

# image files
- url: /(.*\.(bmp|gif|ico|jpeg|jpg|png))
  static_files: static/\1
  upload: static/(.*\.(bmp|gif|ico|jpeg|jpg|png))

- url: (.*)/
  static_files: static\1/index.html
  upload: static/index.html

libraries:
- name: webapp2
  version: "2.5.2"
